
spring:
  application:
    name: service-feign
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#feign\u96C6\u6210\u4E86ribbon\uFF0C\u81EA\u5DF1\u5C31\u80FD\u591F\u7194\u65AD  \u5F00\u542F\u7194\u65AD\u673A\u5236
feign:
  hystrix:
    enabled: true
